spring:
  application:
    name: example
  datasource:
    url: jdbc:oracle:thin:@server:1521/DB_NAME
    username:
    password:
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
management:
  endpoint:
    health:
      show-details: always
custom:
  project:
    credit-accounts:
      - target_brian
    excluded-accounts:
      - test_brian