spring:
  application:
    name: example
  profiles:
    active: local
management:
  endpoint:
    health:
      show-details: always
custom:
  project:
    credit-accounts:
      - target_brian
    excluded-accounts:
      - test_brian