spring:
  application:
    name: example
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: henninb
    password: monday1
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
management:
  endpoint:
    health:
      show-details: always
custom:
  project:
    credit-accounts:
      - target_brian
    excluded-accounts:
      - test_brian