spring:
  application:
    name: example
  datasource:
    url: jdbc:oracle:thin:@ed90-scan1.target.com:1521/DDDTST04
    username: dist
    password:
  profiles:
    active: local
management:
  endpoint:
    health:
      show-details: always
custom:
  project:
    credit-accounts:
      - target_brian
    excluded-accounts:
      - test_brian